# Generated by Django 2.1.3 on 2019-01-25 13:44

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(default='http://webcourse.cs.hut.fi/example_game.html'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='game_state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='result',
            field=models.BooleanField(),
        ),
    ]
