# Generated by Django 2.1.3 on 2019-01-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190110_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(default='http://webcourse.cs.hut.fi/example_game.html'),
        ),
    ]
