# Generated by Django 2.1.3 on 2019-01-18 11:19

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='result',
            field=models.BooleanField(),
        ),
    ]
