# Generated by Django 2.1.3 on 2019-02-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190129_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure')], default='No category', max_length=256),
        ),
    ]
